### PR TITLE
Bump the kpl

### PR DESCRIPTION
**Pull request by gregsterin**
Kinesis Producer Library has a required upgrade due to an AWS cert migration, so needs to be updated before Feb 9: https://github.com/awslabs/amazon-kinesis-producer#required-upgrade.

Bumping KPL to the latest.

Also changed the gemspec to not require git to install the gem, and removed the manual jars in this repo in favor of pulling them from the maven repo when you bundle install.

@samcday

### CODE REVIEW

**Comment by samcday** [comment]
I'm not sure I'm keen on the change to how JARs are handled. If I understand it correctly, it means if you were to install this gem and for whatever reason you're able to reach RubyGems (or have the .gem file) but can't access Maven Central, the installation will fail right?

**Comment by gregsterin** [comment]
@samcday no, you don't need access to Maven when installing the gem. The jars get baked into the gem, but they get pulled from maven as part of the build rather than being included statically from the repo. I can change it back, but this seemed more manageable with respect to not having to pack all the jars into github, and I think I even saw a comment when they were checked in along the lines of "this sucks, but whatever :-)"

**Comment by samcday** [comment]
@gregsterin super late reply, I know, sorry about that :( I'm not seeing the behaviour you describe, maybe I'm doing something wrong?

```
$ gem build logstash-output-kinesis
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.FilenoUtil to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.FilenoUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
WARNING:  license value 'Apache License (2.0)' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
Did you mean 'Apache-2.0'?
WARNING:  open-ended dependency on logstash-devutils (>= 0, development) is not recommended
  if logstash-devutils is semantically versioned, use:
    add_development_dependency 'logstash-devutils', '~> 0'
WARNING:  open-ended dependency on jar-dependencies (>= 0) is not recommended
  if jar-dependencies is semantically versioned, use:
    add_runtime_dependency 'jar-dependencies', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: logstash-output-kinesis
  Version: 5.1.1
  File: logstash-output-kinesis-5.1.1-java.gem

$ tar --to-stdout -xf logstash-output-kinesis-5.1.1-java.gem data.tar.gz | tar -zt
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Gemfile
LICENSE
README.md
lib/logstash-output-kinesis/version.rb
lib/logstash-output-kinesis_jars.rb
lib/logstash/outputs/kinesis.rb
logstash-output-kinesis.gemspec
spec/outputs/kinesis_spec.rb
spec/spec_helper.rb
```

As you can see, the resulting gem file does *not* contain the jars.

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!

**Pull request closed without merging**
