### PR TITLE
Bump KPL to 0.13.1 and aws-sdk-sts to 1.11.631

### PR DESCRIPTION
**Pull request by rodgjame**

### CODE REVIEW

**Comment by rodgjame** [comment]
Is there anyone with write access who can approve this merge?

**Comment by rodgjame** [comment]
Is this a dead project? There are people who want to contribute but can't because they don't have the permissions to merge in code. This pull request has been open for almost 2 months!!!

**Comment by Randy-312** [comment]
So... who is going to test this first!

**Comment by samcday** [comment]
Hi there, I'm archiving this repo (#51). I'm sorry for whatever protracted length of time I ignored your issue/PR for!

**Pull request closed without merging**
