### PR TITLE
Bump KPL to 0.12.6

### PR DESCRIPTION
**Pull request by Jackyjjc**
Amazon is discontinuing KPL older than 0.12.6 on 9th of Feb: https://docs.aws.amazon.com/streams/latest/dev/kinesis-kpl-upgrades.html

### CODE REVIEW

**Comment by Jackyjjc** [comment]
so I guess I do need to check in the jars. I was wondering why there is no vendor/ directory in the branch

**Comment by samcday** [comment]
I've merged this but the automated publish process seems to be broken on `2.x` branch atm. I'm gonna poke around and figure out what's going on but might not get onto it right away. Do you need this version available critically or are you using the `5.1.x` version series anyway?

**Comment by samcday** [comment]
Scratch that. `v2.1.1` is published 🎉

**Comment by Jackyjjc** [comment]
Thanks Sam!

**Pull request merged**
